"""Generate README.md from data/corpus_index.json + data-medium/corpus_index.json."""
import json
from collections import Counter, defaultdict
from pathlib import Path

sub = json.loads(Path("data/corpus_index.json").read_text(encoding="utf-8"))
med = json.loads(Path("data-medium/corpus_index.json").read_text(encoding="utf-8"))

sub_ins = sorted((r for r in sub if r["verdict"] == "IN"), key=lambda r: r["date"])
sub_outs = sorted((r for r in sub if r["verdict"] == "OUT"), key=lambda r: r["date"])
med_ins = sorted((r for r in med if r["verdict"] == "IN"), key=lambda r: r["date"])
med_outs = sorted((r for r in med if r["verdict"] == "OUT"), key=lambda r: r["date"])

sub_themes = Counter(t for r in sub_ins for t in r["themes"])
med_themes = Counter(t for r in med_ins for t in r["themes"])
all_themes = sorted(set(sub_themes) | set(med_themes))

def month_key(d):
    y, m, _ = d.split("-")
    return f"{y}-{m}"

def out_months(recs):
    by = defaultdict(list)
    for r in recs:
        by[month_key(r["date"])].append(r)
    return by

sub_out_by_month = out_months(sub_outs)
med_out_by_month = out_months(med_outs)

L = []
L.append("# CSW Context — Craig Wright's Bitcoin Writing, Structured for BSV-Logic Understanding")
L.append("")
L.append("A complete, machine-readable corpus of Craig Wright's Bitcoin-related writing across")
L.append("two eras — his **Medium** blog (2018–2022, the BCH/BSV split, hash war, nChain patent and")
L.append("Satoshi-authorship campaigns) and his **Substack** ([Singular Grit](https://singulargrit.substack.com),")
L.append("2025–2026, the formalised economic and legal theory) — built to feed a downstream agent/MCP")
L.append("with a faithful map of his thinking, modelling and building around Bitcoin, and precisely")
L.append("where it contradicts BTC-mainstream logic.")
L.append("")
L.append("## Corpus at a glance")
L.append("")
L.append("| | Medium (2018–2022) | Substack (2025–2026) | Combined |")
L.append("|---|---|---|---|")
L.append(f"| Posts archived | {len(med)} | {len(sub)} | {len(med) + len(sub)} |")
L.append(f"| Bitcoin-related (summarised) | {len(med_ins)} | {len(sub_ins)} | {len(med_ins) + len(sub_ins)} |")
L.append(f"| Out of scope (classified, with reasons) | {len(med_outs)} | {len(sub_outs)} | {len(med_outs) + len(sub_outs)} |")
L.append("")
L.append("- Medium era: 7 June 2018 → 2022, fetched via Medium's internal `profile/stream` API")
L.append("- Substack era: 8 June 2025 → 12 August 2026, full archive captured via `api/v1/archive`")
L.append("- 2 paywalled Substack IN posts summarised from free previews (noted in their files)")
L.append("- 1 Medium post (`re-moxie-on-web3`) flagged as a probable Mike Hearn essay misfiled")
L.append("  under Craig's account — summarised but excluded from evidence of his positions")
L.append("")
L.append("## Repository layout")
L.append("")
L.append("```")
L.append("README.md                  this file")
L.append("SYNTHESIS.md               thematic synthesis: ten pillars, reasoning methods, contradiction map")
L.append("CONTRADICTIONS.md          consistency audit: internal (2 lenses), external (BRC guide), cross-era")
L.append("summaries/                 201 Substack essay summaries (YAML frontmatter + fixed template)")
L.append("summaries-medium/          275 Medium essay summaries (same template)")
L.append("topics/                    both eras batched into 26 subject directories + _review/ watch-list")
L.append("canvases/                  interactive canvas presentation of the corpus")
L.append("data/")
L.append("  corpus_index.json        Substack master index: verdict, reason, themes, summary path, URL")
L.append("  contradictions.json      unified machine-readable consistency audit")
L.append("  contradictions/          raw audit inputs (internal tech/econ, external BRC, cross-era)")
L.append("  archive.json             raw Substack archive metadata")
L.append("  classification.json      Substack per-post IN/OUT verdicts with reasons")
L.append("  digest.md                compact digest of all Substack core theses")
L.append("  posts/raw|text/          full Substack post JSON + plain-text conversions")
L.append("data-medium/               the same for Medium: corpus_index.json, archive.json,")
L.append("                           classification.json, posts/json|text/")
L.append("scripts/                   the pipeline (fetch → triage → classify → summarise → index → topics)")
L.append("```")
L.append("")
L.append("## Methodology")
L.append("")
L.append("Both phases ran the same five-stage pipeline:")
L.append("")
L.append("1. **Enumerate** — Substack: `api/v1/archive` paginated to exhaustion (482 posts).")
L.append("   Medium: internal `profile/stream` API paginated by post ID (311 posts), driven through")
L.append("   `curl.exe` with browser headers to pass Medium's TLS fingerprinting.")
L.append("2. **Fetch** — full post bodies (Substack `api/v1/posts/{slug}`; Medium `posts/{postId}`),")
L.append("   HTML/structured JSON converted to text.")
L.append("3. **Triage** — weighted keyword scan as a first pass only; analogy-driven essays score low")
L.append("   despite being core, so no score threshold was trusted.")
L.append("4. **Classify** — parallel LLM agents classified every post from title+subtitle, reading the")
L.append("   body where uncertain; low-confidence verdicts manually reviewed.")
L.append("5. **Summarise** — parallel agents, each reading full texts and writing to a fixed template:")
L.append("   core thesis · key arguments (names/numbers/mechanisms) · reasoning method · BTC-mainstream")
L.append("   divergences · verbatim quotes · connections. UK English; no invented content; excerpts and")
L.append("   stub posts flagged honestly.")
L.append("")
L.append("## Theme distribution (combined 476 essays)")
L.append("")
L.append("| Theme | Substack | Medium | Total |")
L.append("|---|---|---|---|")
for t in sorted(all_themes, key=lambda t: -(sub_themes.get(t, 0) + med_themes.get(t, 0))):
    L.append(f"| {t} | {sub_themes.get(t, 0)} | {med_themes.get(t, 0)} | {sub_themes.get(t, 0) + med_themes.get(t, 0)} |")
L.append("")
L.append("(Essays carry 2–4 tags, so totals exceed essay counts.)")
L.append("")
L.append("## The 201 Substack essays (2025–2026, chronological)")
L.append("")
L.append("| Date | Title | Themes | Summary |")
L.append("|---|---|---|---|")
for r in sub_ins:
    title = r["title"].replace("|", "\\|")
    themes = ", ".join(r["themes"])
    L.append(f"| {r['date']} | [{title}]({r['url']}) | {themes} | [summary]({r['summary']}) |")
L.append("")
L.append("## The 275 Medium essays (2018–2022, chronological)")
L.append("")
L.append("| Date | Title | Themes | Summary |")
L.append("|---|---|---|---|")
for r in med_ins:
    title = r["title"].replace("|", "\\|")
    themes = ", ".join(r["themes"])
    L.append(f"| {r['date']} | [{title}]({r['url']}) | {themes} | [summary]({r['summary']}) |")
L.append("")
L.append("## Out-of-scope posts")
L.append("")
L.append(f"{len(sub_outs)} Substack and {len(med_outs)} Medium posts classified OUT with per-post reasons in the")
L.append("respective `corpus_index.json`. Representative titles per month:")
L.append("")
L.append(f"### Substack OUT ({len(sub_outs)})")
L.append("")
for mk in sorted(sub_out_by_month):
    posts = sub_out_by_month[mk]
    L.append(f"<details><summary><b>{mk}</b> — {len(posts)} posts</summary>")
    L.append("")
    for r in posts:
        title = r["title"].replace("|", "\\|")
        L.append(f"- [{title}]({r['url']}) — *{r['classifier_reason']}*")
    L.append("")
    L.append("</details>")
    L.append("")
L.append(f"### Medium OUT ({len(med_outs)})")
L.append("")
for mk in sorted(med_out_by_month):
    posts = med_out_by_month[mk]
    L.append(f"<details><summary><b>{mk}</b> — {len(posts)} posts</summary>")
    L.append("")
    for r in posts:
        title = r["title"].replace("|", "\\|")
        L.append(f"- [{title}]({r['url']}) — *{r['classifier_reason']}*")
    L.append("")
    L.append("</details>")
    L.append("")

Path("README.md").write_text("\n".join(L), encoding="utf-8")
print(f"README.md written: {len(L)} lines | substack {len(sub_ins)} IN/{len(sub_outs)} OUT | medium {len(med_ins)} IN/{len(med_outs)} OUT")
